server:
  port: 8081

spring:
  main:
    web-application-type: reactive
  application:
    name: cloud-gateway-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

logging:
  level:
    root: debug
  config: classpath:logback-spring.xml